CREATE DATABASE IF NOT EXISTS shopcook;
USE shopcook;
CREATE TABLE IF NOT EXISTS ingredients(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nutriscore FLOAT,
    calories INT
    );
CREATE TABLE IF NOT EXISTS recipes(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image VARCHAR(255),
    calories INT
    time_to_make VARCHAR(255) NOT NULL
    );
CREATE TABLE  IF NOT EXISTS user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
