package l3.miage.shopcook.Controllers;

import java.io.IOException;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.view.RedirectView;

import jakarta.servlet.http.HttpServletResponse;
import l3.miage.shopcook.ingredients.Ingredient;
import l3.miage.shopcook.repositories.IngredientRepository;



@RestController
@RequestMapping(path = "/ingredients") // This means URL's start with /demo (after Application path)
public class IngredientController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private IngredientRepository ingredientRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public RedirectView  addNewIngredient(@RequestParam String name,
            @RequestParam float nutriscore, @RequestParam int calories, HttpServletResponse response) throws IOException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        // List<DietaryRestriction> dietaryRestrictionsList = new ArrayList<>();
        // for (String s : dietaryRestrictions.split(";")) {
        //     dietaryRestrictionsList.add(new DietaryRestriction(s));
        // }
        Ingredient i = new Ingredient();
        i.setName(name);
        // i.setDietaryRestrictions(dietaryRestrictionsList);
        i.setNutriscore(nutriscore);
        i.setCalories(calories);
        ingredientRepository.save(i);
        return new RedirectView ("/ingredients/");
    }

   @GetMapping(path = "/all")
    public List<Ingredient> getAllIngredients() {
        // This returns a JSON or XML with the users
        return ingredientRepository.findAll();
    }


 

    
}
